name: development

on:
  push:
    branches: ["development"]

jobs:
  development:
    #if: true #set false to disable job
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ vars.UPLOAD_PATH }}
            git fetch
            git pull origin development
            git checkout development
            git status
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            php artisan migrate --force
            php artisan db:seed --force